/** Auto-generated by scripts/batch-city-videos.mjs */
export interface CityVideoMeta {
  youtubeId?: string;
  title: string;
  url?: string;
  localSrc?: string;
}

/** YouTube / local embeds for /local-seo/{city}/ pages */
export const cityLocalSeoVideos: Record<string, CityVideoMeta> = {
  'aliso-viejo': {
    youtubeId: 'RlcYXzguTTo',
    title: "Local SEO in Aliso Viejo, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=RlcYXzguTTo',
    localSrc: "/videos/pages/local-seo-aliso-viejo.mp4",
  },
  'anaheim': {
    youtubeId: 'Ihz4sTBtzH8',
    title: "Local SEO in Anaheim, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=Ihz4sTBtzH8',
    localSrc: "/videos/pages/local-seo-anaheim.mp4",
  },
  'brea': {
    youtubeId: '8mwT9hgdjmc',
    title: "Local SEO in Brea, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=8mwT9hgdjmc',
    localSrc: "/videos/pages/local-seo-brea.mp4",
  },
  'costa-mesa': {
    youtubeId: 'zPNEjF_HHaA',
    title: "Local SEO in Costa Mesa, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=zPNEjF_HHaA',
    localSrc: "/videos/pages/local-seo-costa-mesa.mp4",
  },
  'dana-point': {
    youtubeId: 'PXPwYnCiKHY',
    title: "Local SEO in Dana Point, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=PXPwYnCiKHY',
    localSrc: "/videos/pages/local-seo-dana-point.mp4",
  },
  'fountain-valley': {
    youtubeId: 'zP4wavSYhR0',
    title: "Local SEO in Fountain Valley, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=zP4wavSYhR0',
    localSrc: "/videos/pages/local-seo-fountain-valley.mp4",
  },
  'fullerton': {
    youtubeId: 'i8cxZuPEKMs',
    title: "Local SEO in Fullerton, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=i8cxZuPEKMs',
    localSrc: "/videos/pages/local-seo-fullerton.mp4",
  },
  'garden-grove': {
    youtubeId: 'UjTmuOaq2gs',
    title: "Local SEO in Garden Grove, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=UjTmuOaq2gs',
    localSrc: "/videos/pages/local-seo-garden-grove.mp4",
  },
  'huntington-beach': {
    youtubeId: '2X8HRarFpIs',
    title: "Local SEO in Huntington Beach, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=2X8HRarFpIs',
    localSrc: "/videos/pages/local-seo-huntington-beach.mp4",
  },
  'irvine': {
    youtubeId: 'KJZd3hleF5M',
    title: "Local SEO in Irvine, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=KJZd3hleF5M',
    localSrc: "/videos/pages/local-seo-irvine.mp4",
  },
  'laguna-beach': {
    youtubeId: 'MtAA2GIk29A',
    title: "Local SEO in Laguna Beach, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=MtAA2GIk29A',
    localSrc: "/videos/pages/local-seo-laguna-beach.mp4",
  },
  'laguna-hills': {
    youtubeId: '_o50KYiBfTo',
    title: "Local SEO in Laguna Hills, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=_o50KYiBfTo',
    localSrc: "/videos/pages/local-seo-laguna-hills.mp4",
  },
  'laguna-niguel': {
    youtubeId: '4ykFtgogh4A',
    title: "Local SEO in Laguna Niguel, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=4ykFtgogh4A',
    localSrc: "/videos/pages/local-seo-laguna-niguel.mp4",
  },
  'lake-forest': {
    youtubeId: 'RoRJ1qVDjIA',
    title: "Local SEO in Lake Forest, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=RoRJ1qVDjIA',
    localSrc: "/videos/pages/local-seo-lake-forest.mp4",
  },
  'mission-viejo': {
    youtubeId: 'RXnXsSlhy0w',
    title: "Local SEO in Mission Viejo, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=RXnXsSlhy0w',
    localSrc: "/videos/pages/local-seo-mission-viejo.mp4",
  },
  'newport-beach': {
    youtubeId: 'OHda87PJiR8',
    title: "Local SEO in Newport Beach, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=OHda87PJiR8',
    localSrc: "/videos/pages/local-seo-newport-beach.mp4",
  },
  'orange': {
    youtubeId: '9-8R3kb8mmo',
    title: "Local SEO in Orange, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=9-8R3kb8mmo',
    localSrc: "/videos/pages/local-seo-orange.mp4",
  },
  'rancho-santa-margarita': {
    youtubeId: '19RwFxTGxfg',
    title: "Local SEO in Rancho Santa Margarita, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=19RwFxTGxfg',
    localSrc: "/videos/pages/local-seo-rancho-santa-margarita.mp4",
  },
  'san-clemente': {
    youtubeId: 'QFGAqYI1-n0',
    title: "Local SEO in San Clemente, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=QFGAqYI1-n0',
    localSrc: "/videos/pages/local-seo-san-clemente.mp4",
  },
  'san-juan-capistrano': {
    youtubeId: 'rDdgOHlrqWQ',
    title: "Local SEO in San Juan Capistrano, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=rDdgOHlrqWQ',
    localSrc: "/videos/pages/local-seo-san-juan-capistrano.mp4",
  },
  'santa-ana': {
    youtubeId: 'Tg0L3pNz0ZU',
    title: "Local SEO in Santa Ana, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=Tg0L3pNz0ZU',
    localSrc: "/videos/pages/local-seo-santa-ana.mp4",
  },
  'tustin': {
    youtubeId: 'r2v4jbPNYfs',
    title: "Local SEO in Tustin, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=r2v4jbPNYfs',
    localSrc: "/videos/pages/local-seo-tustin.mp4",
  },
  'westminster': {
    youtubeId: 'mIOYgRI7RWU',
    title: "Local SEO in Westminster, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=mIOYgRI7RWU',
    localSrc: "/videos/pages/local-seo-westminster.mp4",
  },
  'yorba-linda': {
    youtubeId: '6yjSsXtSUOA',
    title: "Local SEO in Yorba Linda, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=6yjSsXtSUOA',
    localSrc: "/videos/pages/local-seo-yorba-linda.mp4",
  },
};
