/** Auto-generated by scripts/batch-city-videos.mjs */
import type { CityVideoMeta } from './cityVideos';

export type { CityVideoMeta };

/** YouTube / local embeds for /web-design/{city}/ pages */
export const cityWebDesignVideos: Record<string, CityVideoMeta> = {
  'aliso-viejo': {
    youtubeId: 'oUILzQX49qA',
    title: "Web Design in Aliso Viejo, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=oUILzQX49qA',
    localSrc: "/videos/pages/web-design-aliso-viejo.mp4",
  },
  'anaheim': {
    youtubeId: 'njQN1Nim_g4',
    title: "Web Design in Anaheim, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=njQN1Nim_g4',
    localSrc: "/videos/pages/web-design-anaheim.mp4",
  },
  'brea': {
    youtubeId: 'MS-JeCLY-24',
    title: "Web Design in Brea, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=MS-JeCLY-24',
    localSrc: "/videos/pages/web-design-brea.mp4",
  },
  'costa-mesa': {
    youtubeId: 'RuOQQNWrOLM',
    title: "Web Design in Costa Mesa, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=RuOQQNWrOLM',
    localSrc: "/videos/pages/web-design-costa-mesa.mp4",
  },
  'dana-point': {
    youtubeId: 'n-aMcupp1Gs',
    title: "Web Design in Dana Point, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=n-aMcupp1Gs',
    localSrc: "/videos/pages/web-design-dana-point.mp4",
  },
  'fountain-valley': {
    youtubeId: 'gxOv5aneGcU',
    title: "Web Design in Fountain Valley, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=gxOv5aneGcU',
    localSrc: "/videos/pages/web-design-fountain-valley.mp4",
  },
  'fullerton': {
    youtubeId: 'LmB6HEkGPg0',
    title: "Web Design in Fullerton, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=LmB6HEkGPg0',
    localSrc: "/videos/pages/web-design-fullerton.mp4",
  },
  'garden-grove': {
    youtubeId: 'BzOdNwiUATk',
    title: "Web Design in Garden Grove, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=BzOdNwiUATk',
    localSrc: "/videos/pages/web-design-garden-grove.mp4",
  },
  'huntington-beach': {
    youtubeId: 'tOn5AaenD2M',
    title: "Web Design in Huntington Beach, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=tOn5AaenD2M',
    localSrc: "/videos/pages/web-design-huntington-beach.mp4",
  },
  'irvine': {
    youtubeId: 'yzPAFA50QIs',
    title: "Web Design in Irvine, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=yzPAFA50QIs',
    localSrc: "/videos/pages/web-design-irvine.mp4",
  },
  'laguna-beach': {
    youtubeId: 'Q44CLeKYC9M',
    title: "Web Design in Laguna Beach, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=Q44CLeKYC9M',
    localSrc: "/videos/pages/web-design-laguna-beach.mp4",
  },
  'laguna-hills': {
    youtubeId: 'FvNqiYRJ9mQ',
    title: "Web Design in Laguna Hills, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=FvNqiYRJ9mQ',
    localSrc: "/videos/pages/web-design-laguna-hills.mp4",
  },
  'laguna-niguel': {
    youtubeId: '3pbs-eS4FR8',
    title: "Web Design in Laguna Niguel, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=3pbs-eS4FR8',
    localSrc: "/videos/pages/web-design-laguna-niguel.mp4",
  },
  'lake-forest': {
    youtubeId: 'A-Miee0W_6I',
    title: "Web Design in Lake Forest, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=A-Miee0W_6I',
    localSrc: "/videos/pages/web-design-lake-forest.mp4",
  },
  'mission-viejo': {
    youtubeId: 'YEr7ZX2mnyM',
    title: "Web Design in Mission Viejo, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=YEr7ZX2mnyM',
    localSrc: "/videos/pages/web-design-mission-viejo.mp4",
  },
  'newport-beach': {
    youtubeId: 'ZFuKKNk12xg',
    title: "Web Design in Newport Beach, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=ZFuKKNk12xg',
    localSrc: "/videos/pages/web-design-newport-beach.mp4",
  },
  'orange': {
    youtubeId: 'aBt8i47M8eQ',
    title: "Web Design in Orange, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=aBt8i47M8eQ',
    localSrc: "/videos/pages/web-design-orange.mp4",
  },
  'rancho-santa-margarita': {
    youtubeId: 'yYBFLuBauFo',
    title: "Web Design in Rancho Santa Margarita, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=yYBFLuBauFo',
    localSrc: "/videos/pages/web-design-rancho-santa-margarita.mp4",
  },
  'san-clemente': {
    youtubeId: '60cVEGlg60s',
    title: "Web Design in San Clemente, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=60cVEGlg60s',
    localSrc: "/videos/pages/web-design-san-clemente.mp4",
  },
  'san-juan-capistrano': {
    youtubeId: 'LQWXzyCANAY',
    title: "Web Design in San Juan Capistrano, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=LQWXzyCANAY',
    localSrc: "/videos/pages/web-design-san-juan-capistrano.mp4",
  },
  'santa-ana': {
    youtubeId: 'uTLiBAw-5wA',
    title: "Web Design in Santa Ana, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=uTLiBAw-5wA',
    localSrc: "/videos/pages/web-design-santa-ana.mp4",
  },
  'tustin': {
    youtubeId: 'M_I7rCGjpJQ',
    title: "Web Design in Tustin, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=M_I7rCGjpJQ',
    localSrc: "/videos/pages/web-design-tustin.mp4",
  },
  'westminster': {
    youtubeId: '7eYwN5JvvMA',
    title: "Web Design in Westminster, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=7eYwN5JvvMA',
    localSrc: "/videos/pages/web-design-westminster.mp4",
  },
  'yorba-linda': {
    youtubeId: 'iKU--j073iw',
    title: "Web Design in Yorba Linda, CA | OCWebPros",
    url: 'https://www.youtube.com/watch?v=iKU--j073iw',
    localSrc: "/videos/pages/web-design-yorba-linda.mp4",
  },
};
